// This file is auto-generated by @hey-api/openapi-ts
// Generated code. Do not edit by hand; run `npm run generate` instead.

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTask, editTask, getTask, listTasks, login, logout, type Options } from '../sdk.gen';
import type { CreateTaskData, CreateTaskError, CreateTaskResponse, EditTaskData, EditTaskError, EditTaskResponse, GetTaskData, GetTaskError, GetTaskResponse, ListTasksData, ListTasksError, ListTasksResponse, LoginData, LoginError, LoginResponse, LogoutData, LogoutError, LogoutResponse } from '../types.gen';

/**
 * Login
 *
 * Start a session. The token is returned here and nowhere else.
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 *
 * End the caller's session; its token is rejected from now on.
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listTasksQueryKey = (options?: Options<ListTasksData>) => createQueryKey('listTasks', options);

/**
 * List Tasks
 *
 * Every task, in urgency order, as it looks now.
 */
export const listTasksOptions = (options?: Options<ListTasksData>) => queryOptions<ListTasksResponse, ListTasksError, ListTasksResponse, ReturnType<typeof listTasksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTasks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTasksQueryKey(options)
});

/**
 * Create Task
 *
 * Create a To do task, due at `due_at`, and return it.
 */
export const createTaskMutation = (options?: Partial<Options<CreateTaskData>>): UseMutationOptions<CreateTaskResponse, CreateTaskError, Options<CreateTaskData>> => {
    const mutationOptions: UseMutationOptions<CreateTaskResponse, CreateTaskError, Options<CreateTaskData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTask({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTaskQueryKey = (options: Options<GetTaskData>) => createQueryKey('getTask', options);

/**
 * Get Task
 *
 * One task by its ID, as it looks now.
 */
export const getTaskOptions = (options: Options<GetTaskData>) => queryOptions<GetTaskResponse, GetTaskError, GetTaskResponse, ReturnType<typeof getTaskQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTask({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTaskQueryKey(options)
});

/**
 * Edit Task
 *
 * Change a task's title, description or due date-time and return it.
 *
 * Only the keys sent change; for an active task, an empty body returns it
 * unchanged. A finished task can't be edited.
 */
export const editTaskMutation = (options?: Partial<Options<EditTaskData>>): UseMutationOptions<EditTaskResponse, EditTaskError, Options<EditTaskData>> => {
    const mutationOptions: UseMutationOptions<EditTaskResponse, EditTaskError, Options<EditTaskData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await editTask({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
