// This file is auto-generated by @hey-api/openapi-ts
// Generated code. Do not edit by hand; run `npm run generate` instead.

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login
 */
export type BodyLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CreateTaskBody
 */
export type CreateTaskBody = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due At
     */
    due_at: string;
};

/**
 * ErrorBody
 */
export type ErrorBody = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    error: ErrorBody;
};

/**
 * TaskResponse
 */
export type TaskResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Due At
     */
    due_at: string;
    status: TaskStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Is Overdue
     */
    is_overdue: boolean;
};

/**
 * TaskStatus
 *
 * Where a task is in its life. The value is what the database stores.
 */
export type TaskStatus = 'to_do' | 'in_progress' | 'done' | 'cancelled';

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: 'bearer';
};

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/api/auth/token';
};

export type LoginErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type CreateTaskData = {
    body: CreateTaskBody;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type CreateTaskErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * Successful Response
     */
    201: TaskResponse;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];
