// This file is auto-generated by @hey-api/openapi-ts
// Generated code. Do not edit by hand; run `npm run generate` instead.

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login
 */
export type BodyLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ErrorBody
 */
export type ErrorBody = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    error: ErrorBody;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: 'bearer';
};

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/api/auth/token';
};

export type LoginErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];
