// This file is auto-generated by @hey-api/openapi-ts
// Generated code. Do not edit by hand; run `npm run generate` instead.

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ErrorBody
 */
export type ErrorBody = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    error: ErrorBody;
};
